version: '3.8'

services:
  app:
    image: adv-tickets-back
    container_name: adv-tickets-back
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - 1300:1300
    volumes:
      - ./:/home/app